/**
 *  job object 
 * job : {
 *  designation : string,
 *  company : string,
 *  rating : string,
 *  reviews : [{review}], // keep it empty
 *  experience : {min : num ,max : num},
 *  education : [string]
 *  salary : string or {min:num,max:num}, //
 *  location : {state : string, place : string},
 *  "job description": string,
 *  "skills": [string],
 *  "postedOn" : date,
 *  "company_logo" : string,
 *  keywords : [string],
 *  role : [string],
 *  WFH : boolean 
 *  }
 */

/**
 * processing 
 * salary can be either a string or an object
 * num with comma sepertor : num.toLocaleString("en-in");
 */
 var Jobs = [
    // jobBycategory : Accounting jobs
    {
        designation : 'CharteredAccountant/Accounts Manager',
        company : 'Accotax Global Solutions',
        experience :{ min:1,max:5},
        education : ['CA','MCOM'],
        salary : 'Not disclosed',
        location : 'Ahmedabad',
        description : 'Looking for a team leader who will be the face of our accounting and compliance team',
        skills: ['MCOM','Income Tax','Accounting','Zoho','Quick Books','Chartered Accountant'],
        postedOn : new Date(2022,0,16),
        role: ['Chartered Accountant']
    },
    {
        designation :'Assistant Manager Finance & Accounts',
        company : 'Dr Lal PathLabs',
        rating : 4.2,
        reviews : [],
        experience : {min: 0, max:2},
        salary : 'Not disclosed',
        location : 'Gurgaon',
        description :'Chartered Accountant required with 2+ year of experience Ad-hoc reviews / MIs / projects a ..',
        education : ['CA'],
        skills : ['Financial Analysis','Accounting', 'KPI Monitoring','Finance','MIS','Financial Planning'],
        postedOn : new Date(2022,0,17),
        role: ['Accounts Manager']
    },
    {
        designation : 'Account Assistant',
        company : 'B.R.Maheswari & Co.LLP, Chartered Ac..',
        experience : {min : 0,max:1},
        salary : 'Not disclosed',
        location: 'Mumbai',
        description : 'Required IPCC /CA Inter onlyWork Experience required : 6 months - 1year minimum Good Acc... ',
        education : ['CA'],
        skills :['Accounting','GST','Accounts','Tally','TDS','Income Tax','IPCC','MIS'],
        postedOn : new Date(2022,0,18),
        role: ['Accountant','Accounts Executive']
    },
    {
        designation : 'Account Manager',
        company : 'Kivo Solutions Private Limited',
        rating: 3.5,
        experience : {min :1,max : 5},
        salary : {min : 600000,max:850000},
        location : 'Mumbai',
        description : 'Reviewing & reconcillation of book in Tally - Taxation compliances like GST,TDS, & PT',
        education : ['CA'],
        skills: ['Finalisation','Ledger Scrutiny','GST','TDS','Excel','Book Keeping','MIS Reporting'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation : 'Accounts Executive',
        company : 'NIHAR INFO GLOBAL LTD',
        rating : 1.8,
        reviews :[],
        experience :{min : 0,max :1},
        salary : 'Not disclosed',
        location : 'Hyderabad',
        description :'Should have strong techinical skills in MS Excel, Tally and Zoho Should have good typing speed ...',
        education : ['Any Graduate'],
        skills : ['Tally','MS Excel','Tally ERP','Zoho'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation:'Chartered Accountant',
        company :'NJ IndiaInvest Pvt Ltd',
        rating : 3.9,
        experience : {min : 1,max : 3},
        salary : {min : 350500,max : 500000},
        location : 'Surat',
        description : 'Roles and Responsibilities Product purchase planning Vendor Management Coordination with...',
        education : ['CA'],
        skills:['Accounting','Purchase Management','Chartered Accountant','Supply Chain Management'],
        postedOn : new Date(2022,0,18)
    },
    // Graphic Designer
    {
        designation : 'S&PP Graphic Designer',
        company : 'Accenture',
        image_url : 'https://www.naukri.com/hotjobs/images/v3/Accen_nov20.gif',
        rating: 4.0,
        experience :{min:1,max:5},
        salary : 'Not disclosed',
        location : 'Bangalore/Bengaluru',
        description :' Job Summary : The Graphics and production senior Analyst print and digital design...',
        education : ['Diploma','Any PG'],
        skills:['Adobe Photoshop','Adobe Illustrator','Adobe InDesign','Senior Management','RFX'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation:'Graphic Designer',
        company:'Concerto Software Systems (P) Ltd',
        rating : 3.9,
        experience : {min : 0,max : 1},
        salary : "Not disclosed",
        location : 'Navi Mumbai',
        description :' Employment Type: Full Time, Permanent, UG : Graduate in any discipline with an added deg...',
        education : ['Any UG'],
        skills : ['graphic design','Illustrator','Photoshop','Coreldraw','management','Dreamweaver','InDesign'],
        postedOn : new Date(2022,0,21)
    },
    {
        designation :'Graphic Designer',
        company : 'DHANGUARD LLC',
        location : 'Noida',
        experience :{min:0,max : 1},
        salary : {min : 175000,max:225000},
        WFH : true,
        description: 'Proven graphic designing experienced',
        education : ['B.Des'],
        skills : ['Graphics','Linkedin','Video Editing','Social Media','Graphic Designing','FaceBook','Marketing'],
        postedOn : new Date(2022,0,18)

    },
    {
        designation : 'Graphic Designer',
        company :'Aspiring CEO Private Limited',
        experience : {min : 0,max : 1},
        salary : {min : 100000,max:150000},
        location : 'Lucknow',
        description : 'Graphic Designers interpret the brand and marketing neeed of clients to drive sales/rev...',
        education : ['Any Graduate'],
        skills : ['Communication Skills','Be creative','Illustrator','Graphic Designing'],
        postedOn : new Date(2021,11,24)
    },
    {
        designation : 'Graphic Designer',
        company: 'Cogneesol',
        rating : 4.3,
        experience : {min : 1,max : 5},
        salary : 'Not disclosed',
        location : 'Mohali',
        description: 'Should know current trends in design. The candidate  must be creative and willing to think...',
        education : ['B-TECT/BE'],
        skills : ['Creative','Illustrator','Corel Draw','Dreamweaver','Photoshop','Graphic Designing'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation : 'Graphic Designer',
        company : 'Redsol Solutions Private Limited',
        experience: {min:1,max:4},
        salary : "Not disclosed",
        location :'Remote',
        description :'Proficiency with required desktop publishing tools like Photoshop, InDesign Quark, and..',
        education :['Any Graduate','Any Postgraduate'],
        skills :['graphic design','InDesign Quark','Photoshop','Indesign','Illustrator','Figma','Adobe XD'],
        postedOn : new Date(2022,0,14),
    },
    // browse by non it animation
    {
        designation:'3D Animation Artist',
        company:'Snaphunt',
        image_url :'https://img.naukri.com/logo_images/v3/5212122.gif',
        experience: {min:0,max:3},
        salary:{min:175000,max:375000},
        location:'Mumbai',
        description:'Shoud be Certified Animation Expert Proficient in Rendering setup skills...',
        education : ['Any Graduate','Any PostGraduate'],
        skills:['Video Editing','Rendering','Digital Media','Maya','VFX','AutoCAD 2D','3D Animation','VRAY'],
        postedOn: new Date(2022,0,12)
    },
    {
        designation : 'Graphic/Visual Designer Intern',
        company : 'Delhivery',
        rating : 4.2,
        experience :{min:0,max:3},
        salary : {min:450000,max:650000},
        location : 'Gurgaon/Gurugram',
        description : 'Qualification Pursuing Graduate/ Postgraduate in Instructional Design / Visual Design...',
        education : ['Any Graduate','B.Des'],
        skills : ['2D Animation','Photoshop','Graphic Designing','Instructional Design','Visual Communication'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation : 'IOS Developer',
        company : 'Webknot Technologies Pvt Ltd',
        experience :{ min:1,max:3},
        salary : {min:600000,max:1200000},
        location : 'Bangalore/Bengaluru',
        WFT: true,
        description:'BE / BTech Graduate Goog understanding of MVVM design patter 3 years hand-on experience...',
        education:['Any Graduate'],
        skills:['Swift','XCode','Mobile Application Development','API','Swift programming','UI / UX Design'],
        postedOn : new Date(2022,0,18),
    },
    {
        designation :'Visualizer',
        company :'Regaliz India Pvt Ltd',
        rating :3.3,
        image_url: 'https://img.naukri.com/logo_images/v3/1804750.gif',
        experience:{min:1,max:4},
        salary : 'Not disclosed',
        location : 'Bangalore/Bengaluru',
        description: 'As a Visualizer you must be able to generate ideas and concepts to a brief and / or req...',
        education:['Any Graduate','Any Postgraduate'],
        skills:['Graphics','Graphic designing','adobe creative suite','Manager Technology','Animation'],
        postedOn: new Date(2022,0,17)
    },
    {
        designation : 'Motion Graphic Designer and Video editior',
        company: 'Cyborn Technology Pvt Ltd',
        rating : 4.8,
        experience : {min: 1, max : 5},
        salary : {min:200000,max:300000},
        location: 'Bhopal',
        description: 'We are looking for a passionate Motion Graphics Designer & Video Editor who has a creative...',
        education:['Any Graduate'],
        skills:['Visual Effects','Video Editing','Adobe Premiere Pro','Motion Graphics','Illustrator','Animation'],
        postedOn: new Date(2022,0,18)
    },
    // browse by non it sales
    {
        designation:'Sales Manager',
        company : 'Orbit Sales Marketing',
        experience : {min:1,max:3},
        salary : {min:300000,max:450000},
        location: 'Pune',
        description : 'Education Minimum Graduate Experience Should have atleast 1 year of experience into re...',
        education:['Any Graduate'],
        skills:['Sales','Channel Sales','Sales Management','Business Development','Real Estate Sales'],
        postedOn: new Date(2022,0,19)
    },
    {
        designation : 'Sales & Marketing Executive',
        company : 'SPACE CRAFTS',
        experience : {min:1,max:5},
        salary : {min:225000,max:325000},
        location : 'Chennai',
        description :'Must be flexible to work long hours when required and undertake considerable travel thr...',
        education:['Any Graduate','Any Postgraduate'],
        skills :['Sales','Government','Government Business','Business Development','Corporate Sales'],
        postedOn : new Date(2022,0,18)
    },
    {
        designation: 'Business Development / Sales / BDE MBA Fresher',
        company : 'Nexus Innovative solutions pvt ltd',
        rating:4.0,
        experience:{min:0,max:0},
        salary : {min:200000,max:300000},
        location : 'Chennai',
        description:'Work on all phases of the end-to-end sales cycle including pre-sales presentations,...',
        education:[],
        skills:['Client Management','Sales','sales MBA marketing','Client Servicing','Key Account Management'],
        postedOn: new Date(2022,0,18)
    },
    {
        designation : 'Sales and Marketing Intern',
        company : 'Behing The Screens',
        experience:{min:0,max:1},
        salary :{min:90000,max:100000},
        location : 'Noida',
        description : 'Achieve the targeted sales numbers Require Freshers with....',
        education:['Any Graduate'],
        skills:['B2C Sales','Sales Intern','Directt Sales','Calling','Inside Sales','Internet Sales','Online Sales'],
        postedOn: new Date(2022,0,19)
    },
    {
        designation:'Executive Sales & Marketing',
        company : 'Behind The Screens',
        experience:{min:0,max:1},
        salary :{min:300000,max:400000},
        location : 'Noida',
        description : 'Achieve the targeted sales numbers Require Freshers with....',
        education:['Any Graduate'],
        skills:['B2C Sales','Sales Intern','Directt Sales','Calling','Inside Sales','Internet Sales','Online Sales'],
        postedOn: new Date(2022,0,19)
    },
    {
        designation: 'Instagram Sales Executive',
        company : 'Behing The Screens',
        experience:{min:0,max:1},
        salary :{min:90000,max:100000},
        location : 'Noida',
        description : 'Achieve the targeted sales numbers Require Freshers with.....',
        education:['Any Graduate'],
        skills:['Media Sales','New Client Acquisition','B2C Sales','Social Media'],
        postedOn: new Date(2022,0,19)
    },
    {
        designation:'Microland Hiring "Graduate Engineer Trainee"',
        company:'Microland',
        experience: {min:1,max:3},
        salary: {min:175000,max:225000},
        location: 'Mumbai',
        description: 'Education: Minimum Qualification : Any Bachelor Degree (BCA / BCOM / BSC / BA) Candidate...',
        education:['Any Graduate'],
        skills:['Marketing Campaigns','Sales Management','Sales Executive Activities','Hospitality Sales'],
        postedOn: new Date(2022,0,18)
    },


    {
        designation :'Microland Hiring "Graduate Engineer Trainee"',
        company : 'Microland',
        rating : 3.6,
        reviews : [],
        experience : {min: 0, max:0},
        salary : 'Not disclosed',
        location : 'Kolkata',
        description :'Dear candidates, Here is an excellent opportunity for Traineeship program at Microland for.....',
        education : ['B.Tech/B.E.'],
        skills : ['Engineering Graduates', 'Btech freshers','IT Freshers', 'IT Infrastructure Support'],
        postedOn : new Date(2022,0,18),
        role: ['Hardware and Networks - Other']
    },
    {
        
        designation :'Optometrist',
        company : 'Lenskart',
        rating : 3.0,
        reviews : [],
        experience : {min: 0, max:5},
        salary : {min:100000, max:400000},
        location : 'Hyderabad',
        description :'Fresher and Experienced  Optometrist with Bsc and Diploma with minimum 2 years of experience.....',
        education : ['B.sc'],
        skills : ['Eye', 'Contact Lens', 'Sales', 'Issue', 'Optometrist', 'Store Management'],
        postedOn : new Date(2022,0,14),
        role: ['Optometrist']
    },
    {
        
        designation :'Hiring Graduate Fresher -Channel Sales-Pan India',
        company : 'ICICI Securities',
        rating : 3.6,
        reviews : [],
        experience : {min: 0, max:0},
        salary : {min:50000, max:150000},
        location : 'Hyderabad',
        description :'Excellent opportunity for Graduate Freshers as s Trainee at ICICI Securities Ltd.....',
        education : ['Any Graduate'],
        skills : ['Sales Process', 'Accounting', 'Business Generation', 'Banking', 'Channel Sales', 'Customer Satisfaction'],
        postedOn : new Date(2022,0,11),
        role: ['Pre Sales Consultant']
    },
    {
        
        designation :'Amazon Hiring For Abuse Team For Bangalore Location',
        company : 'Amazon',
        rating : 4.2,
        reviews : [],
        experience : {min: 0, max:0},
        salary : "Not disclosed",
        location : 'Hyderabad',
        description :'The Transaction Risk Investigator position relies on excellent judgment to plan and accomplish goals and will work under very.....',
        education : ['Any Graduate'],
        skills : ['financial institutions', 'risk management', 'Transaction Risk Investigator', 'Risk Investigator', 'fresher'],
        postedOn : new Date(2022,0,17),
        role: ['Non - Tech Support - Non Voice'],
        WFH : true, 
    },
    {
        
        designation :'Mainframe Developer',
        company : 'TCS',
        rating : 3.9,
        reviews : [],
        experience : {min:2, max:7},
        salary : "Not disclosed",
        location : 'Kolkata',
        description :'We have an urgent opening for Mainframe developer....',
        education : ['Any Graduate'],
        skills : ['VSAM', 'JCL', 'Db2', 'IMS DC', 'Cics', 'Cobol', 'Easytrieve'],
        postedOn : new Date(2022,0,16),
        role: [ 'Software developer'],
    },
    {
        
        designation :'GENPACT HIRING FOR POWER BI DEVELOPERS – PAN INDIA',
        company : 'Genpact',
        rating :4.0,
        reviews : [],
        experience : {min:4, max:9},
        salary : {min:800000, max:1800000},
        location : 'Bangalore/Bengaluru',
        description :'Extensive Power BI Implementation and Architecting experience including latest version....',
        education : ['B.Tech.B.E'],
        skills : ['Views', 'SSAS', 'SQL Queries', 'Dax', 'SQL Server', 'Performance Tuning', 'Power Bi Desktop'],
        postedOn : new Date(2022,0,17),
        role: [ 'Software developer'],
    },
    {
        
        designation :'Azure Cloud',
        company : 'TCS',
        rating :3.9,
        reviews : [],
        experience : {min:4, max:6},
        salary : "Not disclosed",
        location : 'Pune',
        description :'TCS has always been in the spotlight for being adept in the next big technologies.....',
        education : ['Any Graduate'],
        skills : ['OS Installation', 'Azure', 'NIM', 'Cloud Computing', 'Cloud', 'HACMP'],
        postedOn : new Date(2022,0,17),
        role: [ 'Software developer'],
    },
    {
        
        designation :'Senior Software Engineer Developer',
        company : 'Coforge',
        rating :3.5,
        reviews : [],
        experience : {min:4, max:9},
        salary : {min:800000, max:1800000},
        location : 'Bangalore/Bengaluru',
        description :'Develop, write and implement software programming applications following established .....',
        education : ['B.Tech/B.E.'],
        skills : ['Java', 'J2Ee',  'Hibernate', 'Multithreading', 'Software Development Methodologies', 'Design Patterns'],
        postedOn : new Date(2022,0,17),
        role: [ 'Software developer'],
    },
    {
        
        designation :'Hiring For ServiceNow Orchestrator!',
        company : 'Wipro',
        rating :3.8,
        reviews : [],
        experience : {min:4, max:7},
        salary : "Not disclosed",
        location : 'Chennai',
        description :'Must have at least 5 years experience working on ServiceNow based automation. .....',
        education : ['B.Tech/B.E.'],
        skills : ['Orchestration', 'Powershell', 'Servicenow', 'ITSM', 'Javascript'],
        postedOn : new Date(2022,0,16),
        role: [ 'Software developer'],
    },
    {
        
        designation :'BIM Coordinator / BIM Team Lead/ BIM Engineer Electrical For Chennai',
        company : 'Shapoorji Pllonji Group',
        rating :4.2,
        reviews : [],
        experience : {min:3, max:8},
        salary : {min:300000, max:800000},
        location : 'Chennai',
        description :'Sound knowledge in shop drawing preparation of electrical services such as Lighting, Small power.....',
        education : ['B.Tech/B.E.'],
        skills : ['Team Leading', 'Electricals', 'Electrical Engineering'],
        postedOn : new Date(2022,0,06),
        role: [ 'Engineer'],
    },
    {
        
        designation :'Engineer Software Development',
        company : 'Wipro',
        rating :3.8,
        reviews : [],
        experience : {min:6, max:11},
        salary :"Not disclosed",
        location : 'Bangalore/Bengaluru',
        description :'JD:C/C++ Language, Embedded Linux, Linux Kernel programing.....',
        education : ['B.Tech/B.E.'],
        skills : ['Canalyzer', 'Software Development', 'C', 'GIT', 'Embedded Linux', 'Canoe', 'Linux Kernel'],
        postedOn : new Date(2022,0,19),
        role: [ 'Engineer'],
    },
    {
        
        designation :'Senior Engineer -PWay',
        company : 'AECOM',
        rating :4.1,
        reviews : [],
        experience : {min:2, max:7},
        salary :"Not disclosed",
        location : 'Bangalore/Bengaluru',
        description :'AECOM is a premier, fully integrated professional and technical ....',
        education : ['B.Tech/B.E.'],
        skills : ['Design Development', 'Cost Effective', 'Professional Development'],
        postedOn : new Date(2022,0,17),
        role: [ 'Engineer'],
    },
    {
        
        designation :'Designer – Highways',
        company : 'AECOM',
        rating :4.1,
        reviews : [],
        experience : {min:3, max:8},
        salary :"Not disclosed",
        location : 'Bangalore/Bengaluru',
        description :'AECOM is a premier, fully integrated professional and technical ....',
        education : ['B.Tech/B.E.'],
        skills : ['2D design', 'CAD', '3D design', 'AutoCAd'],
        postedOn : new Date(2022,0,17),
        role: [ 'Engineer'],
    },
    {
        designation :'Materials Researcher - Catalyst',
        company : 'Shell',
        rating :4.2,
        reviews : [],
        experience : {min:3, max:8},
        salary :"Not disclosed",
        location : 'Bangalore/Bengaluru',
        description :'You will be part of the diverse and cross-disciplinary VP-ship that brings together Catalyst....',
        education : ['B.Tech/B.E.'],
        skills : ['site management', 'Materials', 'Catalyst'],
        postedOn : new Date(2022,0,16),
        role: [ 'Engineer'],
    },
     {
    designation: "Remote Coding or Programming Tutor Solidity",
    company: "Shikvix LLC",
    experience: { min: 1, max: 5 },
    salary: "Not disclosed",
    location: "Remote",
    description:
      "Job Description: 1. Seeking tutors proficient in programming languages willing to teach",
    education: ["Graduation Not Required"],
    skills: [
      "C#",
      "C",
      "Ruby Rails",
      "Go",
      "HTML",
      "Mobile Application Development",
      "Teaching",
    ],
    postedOn: new Date(2022, 0, 15),
    role: ["Teacher"],
  },
  {
    designation: "Senior Medical Coder",
    company: "Source To Win Consultancy",
    experience: { min: 1, max: 5 },
    salary: { min: 125000, max: 425000 },
    location: "Remote",
    description:
      "Looking for 1+yrs experience in (E&M ip,op)/ed pro & facility, chennai,bangalore...",
    education: ["Any Graduate"],
    skills: ["CPT", "Medical Coding"],
    postedOn: new Date(2022, 0, 17),
    role: ["Medical Biller", "Coder"],
  },
  {
    designation: "Teacher - Computing Science and Coding",
    company: "Winquest Online class",
    experience: { min: 2, max: 7 },
    salary: { min: 150000, max: 300000 },
    location: "Remote",
    description:
      "We are looking  for teachers in kids IT Coding training like Python,Block Coding, Java...",
    education: ["Any Graduate"],
    skills: [
      "C++",
      "Advanced Java",
      "Artificial Intelligence",
      "Data Mining",
      "HTML",
      "IT",
      "Machine Learning",
    ],
    postedOn: new Date(2022, 0, 13),
    role: ["Computers Teacher"],
  },
  {
    designation: "Unity 3D Game Developer / Coder",
    company: "Sortyout IT Services Private Limited",
    experience: { min: 1, max: 3 },
    salary: { min: 300000, max: 400000 },
    location: "Remote",
    description:
      "Working Time : 7:00 am 2:10 pm ( Monday to Saturday 6 days of working)...",
    education: ["Any Graduate", "Any Postgraduate"],
    skills: ["c#", "3D Game Developer", "Unity3D", "Game Design"],
    postedOn: new Date(2022, 0, 10),
    role: ["Game Developer", "Programmer"],
  },
  {
    designation: "Sr. Medical Coder",
    company: "Avantha Technologies Limited",
    image_url: "https://img.naukri.com/logo_images/v3/4597944.gif",
    experience: { min: 1, max: 4 },
    salary: { min: 400000, max: 800000 },
    location: "Remote",
    WFH: true,
    description:
      "Hiring Sr. Medical Coder | US Healthcare | Helio Next (Avantha Technologies) Work from Home",
    education: ["Any Graduate"],
    skills: ["CPC", "ED Facility", "IPDRG", "SDS", "Surgery", "Medical coder"],
    postedOn: new Date(2022, 0, 13),
    role: ["Medical Biller", "Coder"]
  },
  // location delhi
  {
      designation:'Web Developer',
      company:'One Christ Wellness private limited',
      experience:{min:1,max:2},
      salary:{min:475000,max:600000},
      location: 'Delhi',
      description:'Ability to work in fast-paced environment, learn rapidly and master diverse web tehcnolo...',
      education:['B.Tech/B.E.','M.Tech'],
      skills:['Backend','Web Development','Python','CSS','Wordpress','Javascript','Bootstrap'],
      postedOn: new Date(2022,0,10),
      role:['Software Developer'],
      WFH: true
  },
  {
      designation:'Coding Teacher',
      company:'OnActive Consultant',
      experience:{min:0,max:1},
      salary: 'Not disclosed',
      location:'Delhi',
      description:'WhiteHat Jr will also provide certification for Teacher once she completes the training...',
      education:['BCA','B.Tech/B.E.'],
      skills:['Communication Skills','Presentation Skills','Written Communication','Coding'],
      role:['Technical Trainer'],
      postedOn: new Date(2022,0,5)
  },
  {
      designation:'Senior Staff Engineer, Lead Engineer',
      company:'HI Tides Consulting',
      experience:{min:6,max:9},
      salary: {min:1000000,max:2000000},
      location:'Delhi',
      description:'You should know how to build CI/ CD pipelines allowing everyday release architecture...',
      education:['B.Tech/B.E.','BCA','M.Tech'],
      skills:['CI/CD','SAN','Azure','Development','Linux','AWS','Kubernetes'],
      role:['Cloud System Administartion'],
      postedOn:new Date(2022,0,21)
  },
  {
      designation:'Big Data Developer',
      company:'DOFORT',
      experience:{min:3,max:7},
      salary:{min:1000000,max:2000000},
      location:'Delhi',
      description:'3+ yrs of development experience in Scala & Spark Good to have AWS & Kafka Candid...',
      education:['B.Tech/B.E.','MCA'],
      skills:['Algorithm Design','Data Structures','Spark','AWS','Linux','Kafka','Scala'],
      role:['Big Data Engineer'],
      postedOn:new Date(2022,0,18)
  }  
    

];

// The id property is later used to remove duplicate entries in the filtered data
var n=1;
Jobs.forEach(function (el){
    el.id = n++;
});